# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d14f92019424d9c70ff2dcc3ce21bea72a27debd670cebaea678082ba3c370cd831a1a2aace4d10b6db3f0d0a07c8d7e29deae2e8ed5bed688e01b922cc01e8

test:
  secret_key_base: 6703509b78a584101d2d786cbda85d5cee573a82d83ac75e4d792902346c4d18d4999b1aef6f2032de575607de9eca5226cd1d9685ffba60c999ccacfa572a4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
